### ISSUE TITLE
iOS build fails with Kotlin 2.3.20-Beta

### ISSUE THREAD

**Issue by ch4rl3x** [maplibre/maplibre-compose#744]
### What happened?

We are migrating our Kotlin Multiplatform project to the Koin Compiler plugin (per migration guide). This appears to require Kotlin 2.3.20-Beta1 or Beta2. After upgrading Kotlin to 2.3.20-Beta2, the iOS app no longer builds.

I was able to reproduce the issue in the iOS sample app of MapLibre Compose by only bumping the Kotlin version to 2.3.20-Beta2.

**Steps to Reproduce**

1. Take the MapLibre Compose iOS sample.
2. Upgrade Kotlin to 2.3.20-Beta2.
3. Build the iOS app (arm64 target).

**Actual Result**
The linker fails with:

```bash
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MLNScaleBar", referenced from:
       in DemoApp[2](DemoApp.framework.o)
ld: symbol(s) not found for architecture arm64
```

### Affected Platforms

- [ ] Android
- [x] iOS
- [ ] Desktop (JVM)
- [ ] Browser (JS)
- [ ] Browser (Wasm)

### Platform Version

iOS 26.2

### Library Version

0.12.1

### Sample Code

libs.versions.toml in maplibre-compose/gradle
gradle-kotlin = "2.3.20-Beta2"

**Comment by westnordost** [comment]
Hm, if it works with Kotlin v2.3.10 and doesn't work with the beta2 of v2.3.20, are you sure that this is the right place to post this issue? After all, the ***linker*** fails. Maplibre-compose does not contain any native code, it is built on top of (in this case) MapLibre-native iOS. We can't do anything here.

If you want this bug resolved, I suggest that you create a minimal project with which this can be reproduced (i.e. maybe use maplibre-native ios directly) and post it in the Kotlin bugtracker.

**Comment by westnordost** [comment]
Ah, I notice that you just took the sample, so that's already quite as minimal as it can get. Maybe that would be enough information to post at the kotlin bugtracker.

**Comment by ch4rl3x** [comment]
https://youtrack.jetbrains.com/issue/KT-84678/iOS-linker-error-with-Kotlin-2.3.20-RC-when-using-MapLibre-Undefined-symbol-MLNScaleBar

**Comment by westnordost** [comment]
> Add MapLibre Native to the iOS target
> Add MapLibre Compose to the shared module

Why both? The first shouldn't be necessary.

**Comment by ch4rl3x** [comment]
Is it not necessary to add MapLibre Native to the iOS target?

The documentation (https://maplibre.org/maplibre-compose/getting-started/#set-up-ios) says that MapLibre Native has to be added to the iOS project.

Without MapLibre Native Dependency in XCode:
 -> Framework 'MapLibre' not found

I edited the YouTrack issue to "Add MapLibre Native as Package Dependency in XCode"

**Comment by westnordost** [comment]
Then maybe a misunderstanding. I thought you were talking about the
```kt
iosMain {
    dependencies {
        // ...
    }
}
```
block in the build.gradle.kts

**Comment by SvyatoslavScherbina** [comment]
(Copying [my explanation](https://youtrack.jetbrains.com/issue/KT-84678/K-N-Undefined-symbol-from-SPM-added-ObjC-frameworks-when-linking-iOS-target#focus=Comments-27-13587281.0-0) of the issue here)

The problem is in the MapLibre iOS native library.
The class `MLNScaleBar` is available in the headers but not exported from the dynamic library, because it lacks `MLN_EXPORT` here: https://github.com/maplibre/maplibre-native/blob/35cf39b72f45cfea55a34ffe7358ade5c950a3c5/platform/ios/src/MLNScaleBar.h#L4.

I would argue that this mismatch is a bug in MapLibre, and it can cause problems not only with Kotlin/Native.
For example, even without instantiating the class in Swift, you can get a similar linkage error:
```swift
import MapLibre
import UIKit

func generic<T: UIView>(_ view: T) {
    view.isHidden = true
}

func triggerLinkError(mapView: MLNMapView) {
    generic(mapView.scaleBar)
}
```
->
```text
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MLNScaleBar", referenced from:
       in main.swift.o
ld: symbol(s) not found for architecture arm64
```

Kotlin 2.3.20 enables `genericSafeCasts=true` by default, which just reveals this problem. In general, in order to use some class, it needs to be exported from the library.

**Comment by westnordost** [comment]
Posted issue upstream: https://github.com/maplibre/maplibre-native/issues/4197
