### ISSUE TITLE
It doesn't build on iOS with Kotlin 2.3.20

### ISSUE THREAD

**Issue by michalgwo** [maplibre/maplibre-compose#757]
### What happened?

App using Kotlin 2.3.20 with maplibre-compose dependency doesn't build. I also tried to build maplibre-compose demo app with Kotlin 2.3.20 and it doesn't build as well.

### Affected Platforms

- [ ] Android
- [x] iOS
- [ ] Desktop (JVM)
- [ ] Browser (JS)
- [ ] Browser (Wasm)

### Platform Version

iOS 26.0.1

### Library Version

0.12.1

### Sample Code

Error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MLNScaleBar", referenced from:
       in shared[3252](liborg.maplibre.compose:maplibre-compose-cache.a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by michalgwo** [comment]
Ahh I didn't see #744 
Closing, as most likely Kotlin bug https://youtrack.jetbrains.com/issue/KT-84678/K-N-Undefined-symbol-from-SPM-added-ObjC-frameworks-when-linking-iOS-target
